### PR TITLE
Expose command line options via Minitest.option hash

### PR DESCRIPTION
**Pull request by Ryan1729**
This is an adjustment of PR https://github.com/seattlerb/minitest/pull/657 to use `option`, singular and opposed to `options` plural, as suggested in [this comment](https://github.com/seattlerb/minitest/pull/657#discussion_r88561532).

I did this because I would also like to be able to make all test randomness depend only on the passed seed value. 

https://github.com/seattlerb/minitest/pull/833 is also potentially relevant.

Closes #657

### CODE REVIEW

**Comment by lzap** [comment]
I would really love to have this. I want to hardcode `--verbose` option in my projects.

**Comment by Qqwy** [comment]
I would also love this feature.

Why was the change from `options` -> `option` (singular) made in the last commit?

**Comment by Ryan1729** [comment]
@Qqwy 
> Why was the change from `options` -> `option` (singular) made in the last commit?

I made that change because singular `option` was asked for in [this 2016 comment](https://github.com/minitest/minitest/pull/657#discussion_r88561532) on the original PR. That request was reaffirmed in [this 2019 comment](https://github.com/minitest/minitest/pull/657#discussion_r292366329), so it seemed like making that change might increase the chances of this getting merged.

**Comment by zenspider** [comment]
I absolutely do NOT want options available to tests. Instead, I've exposed the seed being used via `Minitest.seed`.

**Pull request closed without merging**
